// App.js
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { StackDataProvider } from "../utils/StackContext.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hexfork Project catalyst",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StackDataProvider>
          <Navbar />
          <main> {children}</main>
          <Footer />
        </StackDataProvider>
      </body>
    </html>
  );
}
